spring:
  config:
    activate:
      on-profile: secrets

  # Example DB credentials
  datasource:
    username: "local-db-user"
    password: "local-db-pass"

  data:
    mongodb:
      uri: mongodb+srv://order_user:<password>@cluster0.mongodb.net/order-service-db?retryWrites=true&w=majority


# For Kafka SASL
kafka-config:
  sasl-jaas-config: >
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username='YOUR_KAFKA_API_KEY'
    password='YOUR_KAFKA_API_SECRET';
  schema-registry-user-info-key: basic.auth.credentials.source
  schema-registry-user-info: USER_INFO
  schema-registry-basic-auth-user-info-key: schema.registry.basic.auth.user.info
  schema-registry-basic-auth-user-info: "SR_KEY:SR_SECRET"