spring:
  config:
    activate:
      on-profile: secrets

  datasource:
    # Hardcoded DB credentials (for dev/qa/any usage).
    username: your-username
    password: your-password

kafka-config:
  sasl-jaas-config: >
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username='my-secret-kafka-user'
    password='my-secret-kafka-password';