INSERT INTO "product".products (id, name, description, price) VALUES
(uuid_generate_v4(), 'Product 1', 'Description for product 1', 10.00),
(uuid_generate_v4(), 'Product 2', 'Description for product 2', 20.00),
(uuid_generate_v4(), 'Product 3', 'Description for product 3', 30.00),
(uuid_generate_v4(), 'Product 4', 'Description for product 4', 40.00),
(uuid_generate_v4(), 'Product 5', 'Description for product 5', 50.00),
(uuid_generate_v4(), 'Product 6', 'Description for product 6', 60.00),
(uuid_generate_v4(), 'Product 7', 'Description for product 7', 70.00),
(uuid_generate_v4(), 'Product 8', 'Description for product 8', 80.00),
(uuid_generate_v4(), 'Product 9', 'Description for product 9', 90.00),
(uuid_generate_v4(), 'Product 10', 'Description for product 10', 100.00);