server:
  port: 8083

logging:
  level:
    com.mwc: DEBUG

spring:
  # Always include the "secrets" profile so we also load `application-secrets.yml`
  profiles:
    include: secrets
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: user_user
    password: user_password
#    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    url: jdbc:postgresql://34.50.85.51:5432/orderdb?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    driver-class-name: org.postgresql.Driver


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html


# --- Actuator Health Endpoints Configuration ---
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState