swagger: "2.0"
info:
  title: "My API Gateway"
  version: "1.0.0"
host: "api.fadellh.com"
schemes:
  - https

paths:
  /protected-resource:
    get:
      summary: "Access protected resource"
      operationId: getProtectedResource
      security:
        - jwt_auth: []
      responses:
        "200":
          description: "Successful response"
          schema:
            type: object
            properties:
              message:
                type: string
        "401":
          description: "Unauthorized"
        "429":
          description: "Too many requests"
      x-google-backend:
        address: "http://backend-service.default.svc.cluster.local"
      x-google-extensions:
        x-google-ratelimit:
          limit: 100
          interval: 60s
        x-google-jwks_uri:
          jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/jwk/secure-token"

securityDefinitions:
  jwt_auth:
    type: "apiKey"
    name: "x-api-key"
    in: "header"
