apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-secrets
  namespace: default
data:
  application-secrets.yml: |
    spring:
      datasource:
        username: inventory_user
        password: inventory_password
    kafka-config:
      sasl-jaas-config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username='inventory_kafka_user'
        password='inventory_kafka_password';
