apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-secrets
  namespace: default
data:
  SPRING_DATASOURCE_USERNAME: order_user
  SPRING_DATASOURCE_PASSWORD: order_password
  SPRING_DATA_MONGODB_URI: mongodb+srv://order_user:<password>@cluster0.mongodb.net/order-service-db?retryWrites=true&w=majority
  KAFKA-CONFIG_SCHEMA-REGISTRY-BASIC-AUTH-USER-INFO: ""
  SPRING_DATASOURCE_URL: ""
